apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Chart.Name }}.com
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 80
        path: /*