apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Chart.Name }}-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: "2"
    defaultRequest:
      memory: 256Mi
      cpu: "2"
    type: Container
