# Default values for k8s-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: k8s-frontend
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  port: 80
  nodePort: 30050
  type: NodePort

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
    nginx.org/server-snippet: "proxy_ssl_verify off;"
  hosts:
  - host: k8s-frontend.com
    http:
      paths:
      - backend:
          serviceName: k8s-frontend
          servicePort: 80
        path: /*
        
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
