apiVersion: v1
kind: Secret
metadata:
    name: very-secret
type: Opaque
data:
    token: xpsd
    {{ (.Files.Glob "bar/*").AsSecrets | nindent 2 }}
{{/*    token: |-
    {{- .Files.Get "config1.toml" | b64enc }}
*/}}